[[index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"

[[index]]
name = "kaolin-cu126"
url = "https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.8.0_cu126.html"
format = "flat"

index-strategy = "unsafe-best-match"
